--- # This playbook is to install the GIT on the CENTOS machines
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
   - name: Install latest  GIT on the machine
     yum: 
       use_backend: yum3
       name: git
       state: latest
   - name: Install docker related drivers and tools
     yum:
      name: "{{ packages}}" 
     vars:
      packages:
       - device-mapper-persistent-data
       - lvm2
   - name: Adding and installing the docker repo
     shell: curl -fsSL https://get.docker.com/ | sh
   - name: start the docker daemon 
     command: systemctl start docker
   - name: verifying docker daemon is running
     command: systemctl status docker
     register: docker_service
   - debug: 
       var: docker_service.stdout_lines
   - name: creating the  docker group
     group: 
       name: docker
       state: present
   - name: adding the user to docker group
     user:
       name: cloud_user 
       group: docker
   - name: enabing docker daemon on boot
     command: systemctl enable docker

         
